services:
  postgres_jose:
    image: "postgres:14"
    environment:
      - "POSTGRES_USER=jose"
      - "POSTGRES_DB=meubanco"
      - "POSTGRES_PASSWORD=senha123"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./datas/postgres-data:/var/lib/postgresql/data